spring:
  datasource:
    url: jdbc:mysql://${MYSQL_ADDRESS:localhost}/health?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Password123
    tomcat:
      max-active: 5
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate

logging.level:
  pl.hackyeah.nhf.fraud: DEBUG
  org.springframework.web: INFO

logging.file: fraud.log
